repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
  - id: shellcheck
- repo: https://github.com/python-poetry/poetry
  rev: 1.4.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args: ["--no-update"]
- repo: https://github.com/wlritchi/pre-commit-tools-via-poetry
  rev: 1.1.0
  hooks:
  - id: isort
  - id: autoflake
  - id: black
  - id: flake8
  - id: pyright
